### ISSUE TITLE
How to use the features described at readme

### ISSUE THREAD

**Issue by felipevolpone** [bieelsoares/full-static-search#1]
Hey guys, it's a really nice package :)) 👍 

However, I'd like to know how I can use the features described at README ;)

"Create tags to search
Search with promises
Full text search at a static array
Sort array by query"

see u

**Comment by bieelsoares** [comment]
Hey Volpone, nice to talk with you!

Some features are not implemented yet. I will update the README to reflect the reality.
I'm sorry for that.

Bye!

**Comment by bieelsoares** [comment]
Volpone,

I've done the README update. Can you validate to us?

Bye!

**Comment by luanpotter** [comment]
README changed on #d5cbc7 ;)

**Comment by felipevolpone** [comment]
LGTM 👍  thanks!
